# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taps.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QPixmap

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1201, 801)
        Form.setMaximumSize(QtCore.QSize(1201, 801))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget#Form{\n"
"background-color:rgb(0, 0, 58);}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 58);\n"
"color: rgb(255, 255, 255)")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(100, 100))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableStock = QtWidgets.QTableWidget(self.tab)
        self.tableStock.setGeometry(QtCore.QRect(270, 180, 631, 261))
        self.tableStock.setMinimumSize(QtCore.QSize(631, 0))
        self.tableStock.setMaximumSize(QtCore.QSize(631, 16777215))
        self.tableStock.setStyleSheet("color: rgb(0, 0, 0)")
        self.tableStock.setLineWidth(2)
        self.tableStock.setAutoScroll(True)
        self.tableStock.setObjectName("tableStock")
        self.tableStock.setColumnCount(5)
        self.tableStock.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStock.setHorizontalHeaderItem(4, item)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(550, 30, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(370, 140, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.LineEditBuscarStock = QtWidgets.QLineEdit(self.tab)
        self.LineEditBuscarStock.setGeometry(QtCore.QRect(520, 140, 141, 21))
        self.LineEditBuscarStock.setObjectName("LineEditBuscarStock")
        self.buscarStock = QtWidgets.QPushButton(self.tab)
        self.buscarStock.setGeometry(QtCore.QRect(720, 140, 93, 21))
        self.buscarStock.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.buscarStock.setObjectName("buscarStock")
        self.mostrarStock = QtWidgets.QPushButton(self.tab)
        self.mostrarStock.setGeometry(QtCore.QRect(630, 90, 93, 21))
        self.mostrarStock.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.mostrarStock.setObjectName("mostrarStock")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(460, 90, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(340, 460, 131, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(270, 500, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(270, 540, 65, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(270, 580, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(270, 620, 88, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.AgregarStockNom = QtWidgets.QLineEdit(self.tab)
        self.AgregarStockNom.setGeometry(QtCore.QRect(380, 500, 131, 21))
        self.AgregarStockNom.setObjectName("AgregarStockNom")
        self.AgregarStockCanti = QtWidgets.QLineEdit(self.tab)
        self.AgregarStockCanti.setGeometry(QtCore.QRect(380, 540, 131, 21))
        self.AgregarStockCanti.setObjectName("AgregarStockCanti")
        self.AgregarStockPres = QtWidgets.QLineEdit(self.tab)
        self.AgregarStockPres.setGeometry(QtCore.QRect(380, 580, 131, 21))
        self.AgregarStockPres.setObjectName("AgregarStockPres")
        self.AgregarStockSucur = QtWidgets.QLineEdit(self.tab)
        self.AgregarStockSucur.setGeometry(QtCore.QRect(380, 620, 131, 21))
        self.AgregarStockSucur.setObjectName("AgregarStockSucur")
        self.AgregarProducto = QtWidgets.QPushButton(self.tab)
        self.AgregarProducto.setGeometry(QtCore.QRect(360, 660, 93, 21))
        self.AgregarProducto.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.AgregarProducto.setObjectName("AgregarProducto")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(700, 460, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(640, 500, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.ModiStockID = QtWidgets.QLineEdit(self.tab)
        self.ModiStockID.setGeometry(QtCore.QRect(770, 500, 131, 21))
        self.ModiStockID.setObjectName("ModiStockID")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(640, 540, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(640, 620, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.ModiStockCant = QtWidgets.QLineEdit(self.tab)
        self.ModiStockCant.setGeometry(QtCore.QRect(770, 540, 131, 21))
        self.ModiStockCant.setObjectName("ModiStockCant")
        self.ModiStockSucu = QtWidgets.QLineEdit(self.tab)
        self.ModiStockSucu.setGeometry(QtCore.QRect(770, 620, 131, 21))
        self.ModiStockSucu.setObjectName("ModiStockSucu")
        self.ModificarProducto = QtWidgets.QPushButton(self.tab)
        self.ModificarProducto.setGeometry(QtCore.QRect(730, 660, 93, 21))
        self.ModificarProducto.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.ModificarProducto.setObjectName("ModificarProducto")
        self.AlerAgregaStock = QtWidgets.QLabel(self.tab)
        self.AlerAgregaStock.setGeometry(QtCore.QRect(340, 700, 141, 21))
        self.AlerAgregaStock.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlerAgregaStock.setText("")
        self.AlerAgregaStock.setObjectName("AlerAgregaStock")
        self.AlerModiStock = QtWidgets.QLabel(self.tab)
        self.AlerModiStock.setGeometry(QtCore.QRect(710, 700, 141, 21))
        self.AlerModiStock.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlerModiStock.setText("")
        self.AlerModiStock.setObjectName("AlerModiStock")
        self.AlertaBuscarStock = QtWidgets.QLabel(self.tab)
        self.AlertaBuscarStock.setGeometry(QtCore.QRect(840, 140, 141, 21))
        self.AlertaBuscarStock.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlertaBuscarStock.setText("")
        self.AlertaBuscarStock.setObjectName("AlertaBuscarStock")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(640, 580, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.ModiStockPres = QtWidgets.QLineEdit(self.tab)
        self.ModiStockPres.setGeometry(QtCore.QRect(770, 580, 131, 21))
        self.ModiStockPres.setObjectName("ModiStockPres")
        self.AgregarStockNom.raise_()
        self.tableStock.raise_()
        self.label_10.raise_()
        self.label_19.raise_()
        self.LineEditBuscarStock.raise_()
        self.buscarStock.raise_()
        self.mostrarStock.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.AgregarStockCanti.raise_()
        self.AgregarStockPres.raise_()
        self.AgregarStockSucur.raise_()
        self.AgregarProducto.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.ModiStockID.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.ModiStockCant.raise_()
        self.ModiStockSucu.raise_()
        self.ModificarProducto.raise_()
        self.AlerAgregaStock.raise_()
        self.AlerModiStock.raise_()
        self.AlertaBuscarStock.raise_()
        self.label_40.raise_()
        self.ModiStockPres.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(550, 30, 81, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_61.setObjectName("label_61")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(560, 630, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(470, 130, 65, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(470, 170, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(470, 90, 88, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.AgregaVentaID = QtWidgets.QLineEdit(self.tab_3)
        self.AgregaVentaID.setGeometry(QtCore.QRect(580, 90, 131, 21))
        self.AgregaVentaID.setObjectName("AgregaVentaID")
        self.GuardarVenta = QtWidgets.QPushButton(self.tab_3)
        self.GuardarVenta.setGeometry(QtCore.QRect(550, 210, 81, 21))
        self.GuardarVenta.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.GuardarVenta.setObjectName("GuardarVenta")
        self.AgregaVentaCant = QtWidgets.QLineEdit(self.tab_3)
        self.AgregaVentaCant.setGeometry(QtCore.QRect(580, 130, 131, 21))
        self.AgregaVentaCant.setObjectName("AgregaVentaCant")
        self.AgregaVentaSuc = QtWidgets.QLineEdit(self.tab_3)
        self.AgregaVentaSuc.setGeometry(QtCore.QRect(580, 170, 131, 21))
        self.AgregaVentaSuc.setObjectName("AgregaVentaSuc")
        self.TableVentas = QtWidgets.QTableWidget(self.tab_3)
        self.TableVentas.setGeometry(QtCore.QRect(150, 280, 881, 331))
        self.TableVentas.setStyleSheet("color: rgb(0, 0, 0)")
        self.TableVentas.setObjectName("TableVentas")
        self.TableVentas.setColumnCount(7)
        self.TableVentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableVentas.setHorizontalHeaderItem(6, item)
        self.TotalVenta = QtWidgets.QLabel(self.tab_3)
        self.TotalVenta.setGeometry(QtCore.QRect(530, 670, 121, 41))
        self.TotalVenta.setStyleSheet("background-color:rgb(98, 80, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.TotalVenta.setText("")
        self.TotalVenta.setObjectName("TotalVenta")
        self.AlerAgregaVenta = QtWidgets.QLabel(self.tab_3)
        self.AlerAgregaVenta.setGeometry(QtCore.QRect(520, 240, 141, 21))
        self.AlerAgregaVenta.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlerAgregaVenta.setText("")
        self.AlerAgregaVenta.setObjectName("AlerAgregaVenta")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(330, 420, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.BuscarSucursalID = QtWidgets.QLineEdit(self.tab_4)
        self.BuscarSucursalID.setGeometry(QtCore.QRect(510, 420, 151, 21))
        self.BuscarSucursalID.setObjectName("BuscarSucursalID")
        self.BuscarSucursal = QtWidgets.QPushButton(self.tab_4)
        self.BuscarSucursal.setGeometry(QtCore.QRect(750, 420, 93, 21))
        self.BuscarSucursal.setStyleSheet("background-color:rgb(98, 80, 127)")
        self.BuscarSucursal.setObjectName("BuscarSucursal")
        self.tableBuscarSucursal = QtWidgets.QTableWidget(self.tab_4)
        self.tableBuscarSucursal.setGeometry(QtCore.QRect(400, 500, 381, 221))
        self.tableBuscarSucursal.setStyleSheet("color: rgb(0, 0, 0)")
        self.tableBuscarSucursal.setObjectName("tableBuscarSucursal")
        self.tableBuscarSucursal.setColumnCount(3)
        self.tableBuscarSucursal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableBuscarSucursal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBuscarSucursal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBuscarSucursal.setHorizontalHeaderItem(2, item)
        self.label_62 = QtWidgets.QLabel(self.tab_4)
        self.label_62.setGeometry(QtCore.QRect(520, 30, 131, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_62.setObjectName("label_62")
        self.tableSucursal = QtWidgets.QTableWidget(self.tab_4)
        self.tableSucursal.setGeometry(QtCore.QRect(330, 90, 511, 241))
        self.tableSucursal.setStyleSheet("color: rgb(0, 0, 0)")
        self.tableSucursal.setObjectName("tableSucursal")
        self.tableSucursal.setColumnCount(4)
        self.tableSucursal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSucursal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSucursal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSucursal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSucursal.setHorizontalHeaderItem(3, item)
        self.label_63 = QtWidgets.QLabel(self.tab_4)
        self.label_63.setGeometry(QtCore.QRect(440, 360, 291, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_63.setObjectName("label_63")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(520, 460, 141, 21))
        self.label_38.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.TableProve = QtWidgets.QTableWidget(self.tab_2)
        self.TableProve.setGeometry(QtCore.QRect(280, 90, 631, 271))
        self.TableProve.setStyleSheet("color: rgb(0, 0, 0)")
        self.TableProve.setObjectName("TableProve")
        self.TableProve.setColumnCount(5)
        self.TableProve.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableProve.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableProve.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableProve.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableProve.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableProve.setHorizontalHeaderItem(4, item)
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        self.label_64.setGeometry(QtCore.QRect(520, 30, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_64.setObjectName("label_64")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(520, 390, 151, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(420, 440, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(420, 590, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setGeometry(QtCore.QRect(420, 540, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(420, 490, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.NombreProve = QtWidgets.QLineEdit(self.tab_2)
        self.NombreProve.setGeometry(QtCore.QRect(510, 440, 261, 21))
        self.NombreProve.setObjectName("NombreProve")
        self.CorreoProve = QtWidgets.QLineEdit(self.tab_2)
        self.CorreoProve.setGeometry(QtCore.QRect(510, 590, 261, 21))
        self.CorreoProve.setObjectName("CorreoProve")
        self.TeleProve = QtWidgets.QLineEdit(self.tab_2)
        self.TeleProve.setGeometry(QtCore.QRect(510, 540, 261, 21))
        self.TeleProve.setObjectName("TeleProve")
        self.DirecProve = QtWidgets.QLineEdit(self.tab_2)
        self.DirecProve.setGeometry(QtCore.QRect(510, 490, 261, 21))
        self.DirecProve.setObjectName("DirecProve")
        self.AgregarDistribuidor = QtWidgets.QPushButton(self.tab_2)
        self.AgregarDistribuidor.setGeometry(QtCore.QRect(550, 647, 81, 21))
        self.AgregarDistribuidor.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.AgregarDistribuidor.setObjectName("AgregarDistribuidor")
        self.AlertaProve = QtWidgets.QLabel(self.tab_2)
        self.AlertaProve.setGeometry(QtCore.QRect(520, 690, 141, 21))
        self.AlertaProve.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlertaProve.setText("")
        self.AlertaProve.setObjectName("AlertaProve")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_65 = QtWidgets.QLabel(self.tab_5)
        self.label_65.setGeometry(QtCore.QRect(530, 30, 121, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_65.setObjectName("label_65")
        self.TableEmp = QtWidgets.QTableWidget(self.tab_5)
        self.TableEmp.setGeometry(QtCore.QRect(340, 90, 511, 331))
        self.TableEmp.setStyleSheet("color: rgb(0, 0, 0)")
        self.TableEmp.setObjectName("TableEmp")
        self.TableEmp.setColumnCount(4)
        self.TableEmp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableEmp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEmp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEmp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEmp.setHorizontalHeaderItem(3, item)
        self.EliminarEmpID = QtWidgets.QLineEdit(self.tab_5)
        self.EliminarEmpID.setGeometry(QtCore.QRect(480, 480, 151, 21))
        self.EliminarEmpID.setObjectName("EliminarEmpID")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(440, 480, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(560, 440, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(560, 520, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(470, 550, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(470, 590, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        self.label_36.setGeometry(QtCore.QRect(470, 630, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.SalarioEmp = QtWidgets.QLineEdit(self.tab_5)
        self.SalarioEmp.setGeometry(QtCore.QRect(560, 630, 151, 21))
        self.SalarioEmp.setObjectName("SalarioEmp")
        self.EdadEmp = QtWidgets.QLineEdit(self.tab_5)
        self.EdadEmp.setGeometry(QtCore.QRect(560, 590, 151, 21))
        self.EdadEmp.setObjectName("EdadEmp")
        self.NombreEmp = QtWidgets.QLineEdit(self.tab_5)
        self.NombreEmp.setGeometry(QtCore.QRect(560, 550, 151, 21))
        self.NombreEmp.setObjectName("NombreEmp")
        self.AgregarEmpleado = QtWidgets.QPushButton(self.tab_5)
        self.AgregarEmpleado.setGeometry(QtCore.QRect(550, 670, 81, 21))
        self.AgregarEmpleado.setStyleSheet("background-color:rgb(98, 80, 127)")
        self.AgregarEmpleado.setObjectName("AgregarEmpleado")
        self.EliminarEmpleado = QtWidgets.QPushButton(self.tab_5)
        self.EliminarEmpleado.setGeometry(QtCore.QRect(650, 480, 93, 21))
        self.EliminarEmpleado.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.EliminarEmpleado.setObjectName("EliminarEmpleado")
        self.AlertaAgregaEmp = QtWidgets.QLabel(self.tab_5)
        self.AlertaAgregaEmp.setGeometry(QtCore.QRect(510, 710, 141, 21))
        self.AlertaAgregaEmp.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlertaAgregaEmp.setText("")
        self.AlertaAgregaEmp.setObjectName("AlertaAgregaEmp")
        self.AlertaElimEmpleado = QtWidgets.QLabel(self.tab_5)
        self.AlertaElimEmpleado.setGeometry(QtCore.QRect(760, 480, 141, 21))
        self.AlertaElimEmpleado.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlertaElimEmpleado.setText("")
        self.AlertaElimEmpleado.setObjectName("AlertaElimEmpleado")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableVentasRealizada = QtWidgets.QTableWidget(self.tab_6)
        self.tableVentasRealizada.setGeometry(QtCore.QRect(330, 230, 511, 471))
        self.tableVentasRealizada.setStyleSheet("color: rgb(0, 0, 0)")
        self.tableVentasRealizada.setObjectName("tableVentasRealizada")
        self.tableVentasRealizada.setColumnCount(4)
        self.tableVentasRealizada.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableVentasRealizada.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVentasRealizada.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVentasRealizada.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableVentasRealizada.setHorizontalHeaderItem(3, item)
        self.MostrarVentas = QtWidgets.QPushButton(self.tab_6)
        self.MostrarVentas.setGeometry(QtCore.QRect(530, 90, 121, 28))
        self.MostrarVentas.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.MostrarVentas.setObjectName("MostrarVentas")
        self.BuscarVenta = QtWidgets.QPushButton(self.tab_6)
        self.BuscarVenta.setGeometry(QtCore.QRect(670, 150, 93, 21))
        self.BuscarVenta.setStyleSheet("background-color: rgb(98, 80, 127)")
        self.BuscarVenta.setObjectName("BuscarVenta")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(430, 150, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.BuscarVendaID = QtWidgets.QLineEdit(self.tab_6)
        self.BuscarVendaID.setGeometry(QtCore.QRect(490, 150, 141, 21))
        self.BuscarVendaID.setObjectName("BuscarVendaID")
        self.label_66 = QtWidgets.QLabel(self.tab_6)
        self.label_66.setGeometry(QtCore.QRect(480, 30, 221, 36))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("font: 22pt \"Brush Script MT\";")
        self.label_66.setObjectName("label_66")
        self.AlertaBusquedaVenta = QtWidgets.QLabel(self.tab_6)
        self.AlertaBusquedaVenta.setGeometry(QtCore.QRect(530, 190, 141, 21))
        self.AlertaBusquedaVenta.setStyleSheet("color: rgb(255, 8, 12);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.AlertaBusquedaVenta.setText("")
        self.AlertaBusquedaVenta.setObjectName("AlertaBusquedaVenta")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(50, 150, 211, 461))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setPixmap(QPixmap('cande1.jpg'))
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(910, 150, 211, 461))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.setPixmap(QPixmap('cande2.jpg'))
        self.tabWidget.addTab(self.tab_6, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Iluminación Residencial"))
        self.tableStock.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableStock.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableStock.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableStock.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tableStock.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Precio"))
        item = self.tableStock.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Distribuidor"))
        self.label_10.setText(_translate("Form", "Stock"))
        self.label_19.setText(_translate("Form", "ID del producto"))
        self.buscarStock.setText(_translate("Form", "Buscar"))
        self.mostrarStock.setText(_translate("Form", "Mostrar"))
        self.label_20.setText(_translate("Form", "Todos los productos"))
        self.label_21.setText(_translate("Form", "Agregar producto"))
        self.label_22.setText(_translate("Form", "Nombre"))
        self.label_23.setText(_translate("Form", "Cantidad"))
        self.label_24.setText(_translate("Form", "Precio"))
        self.label_25.setText(_translate("Form", "ID Sucursal"))
        self.AgregarProducto.setText(_translate("Form", "Guardar"))
        self.label_26.setText(_translate("Form", "Modificar producto"))
        self.label_27.setText(_translate("Form", "ID producto"))
        self.label_28.setText(_translate("Form", "Cantidad"))
        self.label_29.setText(_translate("Form", "ID sucursal"))
        self.ModificarProducto.setText(_translate("Form", "Guardar"))
        self.AlerAgregaStock.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlerAgregaStock.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.AlerModiStock.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlerModiStock.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.AlertaBuscarStock.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlertaBuscarStock.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_40.setText(_translate("Form", "Precio"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Stock"))
        self.label_61.setText(_translate("Form", "Ventas"))
        self.label_6.setText(_translate("Form", "Total"))
        self.label_7.setText(_translate("Form", "Cantidad"))
        self.label_12.setText(_translate("Form", "ID Sucursal"))
        self.label_13.setText(_translate("Form", "ID Producto"))
        self.GuardarVenta.setText(_translate("Form", "Guardar"))
        item = self.TableVentas.horizontalHeaderItem(0)
        item.setText(_translate("Form", " ID Venta"))
        item = self.TableVentas.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID Producto"))
        item = self.TableVentas.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto"))
        item = self.TableVentas.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Cantidad"))
        item = self.TableVentas.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Precio"))
        item = self.TableVentas.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Total"))
        item = self.TableVentas.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Hora"))
        self.AlerAgregaVenta.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlerAgregaVenta.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Ventas"))
        self.label_9.setText(_translate("Form", "ID de la sucursal"))
        self.BuscarSucursal.setText(_translate("Form", "Buscar"))
        item = self.tableBuscarSucursal.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID Sucursal"))
        item = self.tableBuscarSucursal.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID Producto"))
        item = self.tableBuscarSucursal.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Disponible"))
        self.label_62.setText(_translate("Form", "Sucursales"))
        item = self.tableSucursal.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID Sucursal"))
        item = self.tableSucursal.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableSucursal.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Dirección"))
        item = self.tableSucursal.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Teléfono"))
        self.label_63.setText(_translate("Form", "Productos por Sucursal"))
        self.label_38.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.label_38.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Sucursal"))
        item = self.TableProve.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.TableProve.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.TableProve.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Dirección"))
        item = self.TableProve.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Teléfono"))
        item = self.TableProve.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Correo"))
        self.label_64.setText(_translate("Form", "Proveedores"))
        self.label_30.setText(_translate("Form", "Agregar Distribuidor"))
        self.label_31.setText(_translate("Form", "Nombre"))
        self.label_32.setText(_translate("Form", "Correo"))
        self.label_33.setText(_translate("Form", "Teléfono"))
        self.label_34.setText(_translate("Form", "Dirección"))
        self.AgregarDistribuidor.setText(_translate("Form", "Guardar"))
        self.AlertaProve.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlertaProve.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Distribuidor"))
        self.label_65.setText(_translate("Form", "Empleado"))
        item = self.TableEmp.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.TableEmp.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.TableEmp.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Edad"))
        item = self.TableEmp.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Salario"))
        self.label_15.setText(_translate("Form", "ID"))
        self.label_16.setText(_translate("Form", "Eliminar"))
        self.label_17.setText(_translate("Form", "Agregar"))
        self.label_18.setText(_translate("Form", "Nombre"))
        self.label_35.setText(_translate("Form", "Edad"))
        self.label_36.setText(_translate("Form", "Salario"))
        self.AgregarEmpleado.setText(_translate("Form", "Guardar"))
        self.EliminarEmpleado.setText(_translate("Form", "Guardar"))
        self.AlertaAgregaEmp.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlertaAgregaEmp.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.AlertaElimEmpleado.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlertaElimEmpleado.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Empleado"))
        item = self.tableVentasRealizada.horizontalHeaderItem(0)
        item.setText(_translate("Form", " ID Venta"))
        item = self.tableVentasRealizada.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tableVentasRealizada.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Total"))
        item = self.tableVentasRealizada.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Hora"))
        self.MostrarVentas.setText(_translate("Form", "Mostrar todas"))
        self.BuscarVenta.setText(_translate("Form", "Buscar"))
        self.label_37.setText(_translate("Form", "ID"))
        self.label_66.setText(_translate("Form", "Ventas Realizadas"))
        self.AlertaBusquedaVenta.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Admin o Password incorrectos</span></p></body></html>"))
        self.AlertaBusquedaVenta.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Ventas realizadas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

